# This file originaly comes from https://github.com/0x192/universal-android-debloater/blob/main/.github/workflows/build_artifacts.yml
name: Build artifacts
on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Building ${{ matrix.build_target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - build_target: linux
            os: ubuntu-latest
          - build_target: macos
            os: macos-latest
          - build_target: windows
            os: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      #- uses: rui314/setup-mold@v1 # faster linker
      #  with:
      #    make-default: false
      - name: Install libusb
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install libusb-1.0-0-dev libusb-1.0-0
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target
          key: ${{ runner.os }}-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.OS }}-release-
        if: matrix.os == 'ubuntu-latest'
      - name: Building
        run: cargo build --release
      - name: Creating ./bin directory
        run: mkdir -p bin
      - name: Renaming binaries [Windows]
        if: matrix.os == 'windows-latest'
        run: mv target/release/ok-gpg-agent.exe bin/ok-gpg-agent-${{ matrix.build_target }}.exe
      - name: Renaming binaries [Others]
        if: matrix.os != 'windows-latest'
        run: mv target/release/ok-gpg-agent bin/ok-gpg-agent-${{ matrix.build_target }}
      - name: Tarball Linux binary
        if: matrix.os == 'ubuntu-latest'
        run: tar --remove-files -czf bin/ok-gpg-agent-${{ matrix.build_target }}{.tar.gz,}
      - name: Zip MacOS binary
        if: matrix.os == 'macos-latest'
        run: zip -9rm bin/ok-gpg-agent-${{ matrix.build_target }}{.zip,}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ok-gpg-agent-${{ matrix.build_target }}
          path: bin/ok-gpg-agent-*